# Generated by Django 6.0.3 on 2026-03-10 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salary_min', models.IntegerField(blank=True, max_length=10, null=True)),
                ('salary_max', models.IntegerField(blank=True, max_length=10, null=True)),
                ('fixed_salary', models.IntegerField(blank=True, max_length=10, null=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiter.recruiter')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('fixed_salary__isnull', False), ('salary_max__isnull', True), ('salary_min__isnull', True)), models.Q(('fixed_salary__isnull', True), ('salary_max__isnull', False), ('salary_min__isnull', False)), _connector='OR'), name='enforce_salary_format')],
            },
        ),
    ]
